name: Docker Image CI

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'
  
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.gitlab.com
  # github.repository as <account>/<repo>
  IMAGE_NAME: plxdhong/pass/blog

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
      uses: docker/build-push-action@v2.7.0
      with:
        platforms: linux/amd64
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to Oracle via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Stop all running Docker Containers
          docker stop blog
          # Free up space
          docker rm blog
          # Pull the Docker Image 
          docker pull registry.gitlab.com/plxdhong/pass/blog:main
          # Run a new container from a new image
          docker run -d -p 10180:3000 --name=blog --restart on-failure:5 registry.gitlab.com/plxdhong/pass/blog:main
